In [2]:
import pandas as pd

df = pd.read_csv('/content/customer_shopping_behavior.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.shape

(3900, 18)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.describe

<bound method NDFrame.describe of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))
print("Missing Value :\n", df.isnull().sum())

Missing Value :
 Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()  # turning all column name into lowercase to easily remember
df.columns = df.columns.str.replace(" ","_")  #replacing space betw name by _
df = df.rename(columns={"purchase_amount_(usd)":"purchase_amount"}) #rename the column
print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [16]:
df.to_csv("customer_shopping_behavior.csv" , index=False)  #to update the csv file

In [15]:
# Creating age group::

labels = ["Young","Adults","Middle-Age","Senior"]
df["age_group"] = pd.qcut(df["age"] , q=4 ,labels=labels)
print(df[["age","age_group"]])

      age   age_group
0      55  Middle-Age
1      19       Young
2      50  Middle-Age
3      21       Young
4      45  Middle-Age
...   ...         ...
3895   40      Adults
3896   52  Middle-Age
3897   46  Middle-Age
3898   44      Adults
3899   52  Middle-Age

[3900 rows x 2 columns]

In [14]:
df.to_csv("customer_shopping_behavior.csv" , index=False)
print(df[(df['age_group']=="Senior")]) # condition checking (filter)

      customer_id  age  gender item_purchased     category  purchase_amount  \
6               7   63    Male          Shirt     Clothing               85
12             13   61    Male           Coat    Outerwear               72
13             14   65    Male          Dress     Clothing               51
14             15   64    Male           Coat    Outerwear               53
15             16   64    Male          Skirt     Clothing               81
...           ...  ...     ...            ...          ...              ...
3874         3875   70  Female        Sweater     Clothing               54
3875         3876   63  Female            Hat  Accessories               51
3876         3877   60  Female          Shoes     Footwear               85
3878         3879   60  Female            Hat  Accessories               42
3894         3895   66  Female          Skirt     Clothing               78

            location size   color  season  review_rating subscription_status  \
6            Montana    M    Gray    Fall            3.2                 Yes
12          Delaware    M    Gold  Winter            4.5                 Yes
13     New Hampshire    M  Violet  Spring            4.7                 Yes
14          New York    L    Teal  Winter            4.7                 Yes
15      Rhode Island    M    Teal  Winter            2.8                 Yes
...              ...  ...     ...     ...            ...                 ...
3874          Nevada   XL   Beige  Summer            3.9                  No
3875   New Hampshire    M    Pink  Winter            3.3                  No
3876       Wisconsin    S    Cyan    Fall            2.6                  No
3878  South Carolina    M    Pink  Summer            3.4                  No
3894     Connecticut    L   White  Spring            3.9                  No

       shipping_type discount_applied promo_code_used  previous_purchases  \
6      Free Shipping              Yes             Yes                  49
12           Express              Yes             Yes                  37
13           Express              Yes             Yes                  31
14     Free Shipping              Yes             Yes                  34
15      Store Pickup              Yes             Yes                   8
...              ...              ...             ...                 ...
3874  2-Day Shipping               No              No                  33
3875  2-Day Shipping               No              No                  21
3876  2-Day Shipping               No              No                   7
3878  2-Day Shipping               No              No                  24
3894  2-Day Shipping               No              No                  44

     payment_method frequency_of_purchases age_group
6              Cash              Quarterly    Senior
12            Venmo            Fortnightly    Senior
13           PayPal                 Weekly    Senior
14       Debit Card                 Weekly    Senior
15           PayPal                Monthly    Senior
...             ...                    ...       ...
3874    Credit Card              Bi-Weekly    Senior
3875    Credit Card               Annually    Senior
3876           Cash               Annually    Senior
3878    Credit Card               Annually    Senior
3894    Credit Card         Every 3 Months    Senior

[944 rows x 19 columns]

In [17]:
# creating column purchase_frequency_days

frequency_mapping = {
    'Weekly':7,
    'Fortnightly':14,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months' :90
}

In [18]:
df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)
df.to_csv("customer_shopping_behavior.csv" , index=False)    #file update
print(df[["purchase_frequency_days","frequency_of_purchases"]].head(15))  #checking

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly

In [19]:
# in dataset there 2 column name discount and promo code used if both are same then we need to remove one of it

print((df["discount_applied"]==df["promo_code_used"]).all())  #checking if both same or not (Output : if True means same)

df =df.drop("promo_code_used" , axis=1)
df.to_csv("customer_shopping_behavior.csv" , index=False)
print(df.columns)

True
Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [ ]:
# this code is not running bcs of mysql host is localhost  so this is reference code

# Connecting python file with mysql

import csv
import mysql.connector

# Step 1: Establish the connection
db_connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="shivam",
    database="customer_analysis"
)

cursor = db_connection.cursor()
csv_file_path = 'customer_shopping_behavior.csv'

# Step 2: Open and read the CSV
with open(csv_file_path, mode='r') as file:
    csv_data = csv.reader(file)

    # Skip the header row (highly recommended since your CSV likely has these column names at the top)
    next(csv_data)

    # Step 3: Loop through and insert
    for row in csv_data:
        # Update the query to include all 19 columns and 19 %s placeholders
        # Update the query to include purchase_frequency_days at the end
        sql_insert_query = """
            INSERT INTO customer_purchases (
                customer_id, age, gender, item_purchased, category,
                purchase_amount, location, size, color, season,
                review_rating, subscription_status, shipping_type,
                discount_applied, previous_purchases, payment_method,
                frequency_of_purchases, age_group, purchase_frequency_days
            )
            VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                %s, %s, %s, %s, %s, %s, %s, %s, %s
            )
        """

        # Execute the query with the current row's data
        cursor.execute(sql_insert_query, row)

# Step 4: Commit and close
db_connection.commit()
print(f"Dataset successfully imported into the customer_purchases table!")

cursor.close()
db_connection.close()